AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - gemfiles/*
    - test/dummy_app/**/*
    - vendor/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - actual_db_schema.gemspec

Metrics/MethodLength:
  Max: 15
  Exclude:
    -  test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Enabled: false
