AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - gemfiles/*
    - test/dummy_app/**/*
    - vendor/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - actual_db_schema.gemspec

Metrics/MethodLength:
  Exclude:
    -  test/**/*
