name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    strategy:
      matrix:
        include:
          - { ruby: '2.7', rails: '6.1' }
          - { ruby: '3.0', rails: '6.1' }
          - { ruby: '3.1', rails: '7.0' }
          - { ruby: '3.2', rails: '7.1' }
          - { ruby: '3.3', rails: '7.1' }
          - { ruby: '3.3', rails: 'edge' }
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails.${{ matrix.rails }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec rubocop
